import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import '../../integration_test/walkthrough_fixtures.dart';

/// The macOS walkthrough (`integration_test/macos_walkthrough_test.dart`)
/// imports parser fixtures, but the sandboxed app can't read the source
/// tree, so it carries copies in `integration_test/walkthrough_fixtures.dart`.
/// This keeps the copies equal to `packages/cred_parsers/test/fixtures`.
///
/// After changing a fixture, rewrite the copies with:
///
/// ```sh
/// DEVVAULT_UPDATE_WALKTHROUGH_FIXTURES=1 \
///   flutter test test/tool/walkthrough_fixtures_test.dart
/// ```
void main() {
  const dir = 'packages/cred_parsers/test/fixtures';
  const names = [
    'AuthKey_TESTKEY123.p8',
    'legacy.p12',
    'development.mobileprovision',
    'test.jks',
    'google-services.json',
    'GoogleService-Info.plist',
    'service-account.json',
    'client_secret_000000000000-test.apps.googleusercontent.com.json',
    'id_ed25519',
  ];

  test('the walkthrough carries exact copies of the parser fixtures', () {
    if (Platform.environment['DEVVAULT_UPDATE_WALKTHROUGH_FIXTURES'] != null) {
      final out = StringBuffer()
        ..writeln('// Generated by test/tool/walkthrough_fixtures_test.dart')
        ..writeln('// from packages/cred_parsers/test/fixtures (test-only')
        ..writeln('// files, no real credentials). Do not edit by hand.')
        ..writeln()
        ..writeln("import 'dart:convert';")
        ..writeln("import 'dart:typed_data';")
        ..writeln()
        ..writeln('/// Fixture bytes by file name, for the sandboxed app.')
        ..writeln('Uint8List walkthroughFixture(String name) =>')
        ..writeln('    base64.decode(walkthroughFixtures[name]!);')
        ..writeln()
        ..writeln('const walkthroughFixtures = <String, String>{');
      for (final name in names) {
        final b64 = base64.encode(File('$dir/$name').readAsBytesSync());
        out.writeln("  '$name':");
        for (var i = 0; i < b64.length; i += 72) {
          final end = i + 72 > b64.length ? b64.length : i + 72;
          final last = end == b64.length;
          out.writeln("      '${b64.substring(i, end)}'${last ? ',' : ''}");
        }
      }
      out.writeln('};');
      File('integration_test/walkthrough_fixtures.dart')
          .writeAsStringSync(out.toString());
      return;
    }
    expect(walkthroughFixtures.keys, names);
    for (final name in names) {
      expect(
        walkthroughFixture(name),
        File('$dir/$name').readAsBytesSync(),
        reason: '$name differs: regenerate (see this file)',
      );
    }
  });
}
