import 'package:fluent_ui/fluent_ui.dart' as fl;
import 'package:flutter/cupertino.dart' show CupertinoIcons;
import 'package:flutter/widgets.dart';
import 'package:yaru/yaru.dart' as yaru;

import 'desktop_theme.dart';

/// The icons desktop screens use, by meaning. Each OS draws them from its
/// own set (ADR-0005): SF-style Cupertino icons on macOS, Fluent icons on
/// Windows, Yaru icons on Linux.
enum DesktopSymbol {
  allItems,
  expiring,
  expired,
  conflicts,
  unreadable,
  add,
  importFile,
  tag,
  settings,
  timer,
  lock,
  search,
  synced,
  syncing,
  syncOff,
  syncFailed,
  keyChanged,
  warning,
  chevronRight,
  chevronDown,
  platformApple,
  platformAndroid,
  platformWeb,
  platformServer,
  platformDesktop,
  platformOther,

  // Item types (the vault table and the inspector's type tile).
  typeAuthKey,
  typeCertificate,
  typeProfile,
  typeKeystore,
  typeFirebase,
  typeServiceAccount,
  typeOAuthClient,
  typeSshKey,
  typeFile,
  typeSecret,

  // The inspector: its actions, field buttons and expiry box.
  more,
  copy,
  reveal,
  conceal,
  export,
  check,
  calendar,
  person,
  sortAscending,
  sortDescending;

  IconData of(DesktopKit kit) => switch (kit) {
    DesktopKit.macos => _macos,
    DesktopKit.fluent => _fluent,
    DesktopKit.yaru => _yaru,
  };

  IconData get _macos => switch (this) {
    allItems => CupertinoIcons.square_stack_3d_up,
    expiring => CupertinoIcons.clock,
    expired => CupertinoIcons.xmark_circle,
    conflicts => CupertinoIcons.arrow_merge,
    unreadable => CupertinoIcons.exclamationmark_shield,
    add => CupertinoIcons.plus,
    importFile => CupertinoIcons.tray_arrow_down,
    tag => CupertinoIcons.tag,
    settings => CupertinoIcons.gear,
    timer => CupertinoIcons.timer,
    lock => CupertinoIcons.lock,
    search => CupertinoIcons.search,
    synced => CupertinoIcons.cloud,
    syncing => CupertinoIcons.arrow_2_circlepath,
    syncOff => CupertinoIcons.wifi_slash,
    syncFailed => CupertinoIcons.exclamationmark_triangle,
    keyChanged => CupertinoIcons.lock_rotation,
    warning => CupertinoIcons.exclamationmark_triangle,
    chevronRight => CupertinoIcons.chevron_right,
    chevronDown => CupertinoIcons.chevron_down,
    platformApple => CupertinoIcons.device_phone_portrait,
    platformAndroid => CupertinoIcons.device_phone_portrait,
    platformWeb => CupertinoIcons.globe,
    platformServer => CupertinoIcons.cube_box,
    platformDesktop => CupertinoIcons.desktopcomputer,
    platformOther => CupertinoIcons.cube,
    typeAuthKey => CupertinoIcons.lock_shield,
    typeCertificate => CupertinoIcons.checkmark_seal,
    typeProfile => CupertinoIcons.doc_text,
    typeKeystore => CupertinoIcons.lock_circle,
    typeFirebase => CupertinoIcons.flame,
    typeServiceAccount => CupertinoIcons.person_crop_square,
    typeOAuthClient => CupertinoIcons.shield,
    typeSshKey => CupertinoIcons.chevron_left_slash_chevron_right,
    typeFile => CupertinoIcons.doc,
    typeSecret => CupertinoIcons.staroflife,
    more => CupertinoIcons.ellipsis,
    copy => CupertinoIcons.doc_on_doc,
    reveal => CupertinoIcons.eye,
    conceal => CupertinoIcons.eye_slash,
    export => CupertinoIcons.square_arrow_up,
    check => CupertinoIcons.checkmark,
    calendar => CupertinoIcons.calendar,
    person => CupertinoIcons.person,
    sortAscending => CupertinoIcons.arrow_up,
    sortDescending => CupertinoIcons.arrow_down,
  };

  IconData get _fluent => switch (this) {
    allItems => fl.FluentIcons.stack,
    expiring => fl.FluentIcons.clock,
    expired => fl.FluentIcons.error_badge,
    conflicts => fl.FluentIcons.branch_merge,
    unreadable => fl.FluentIcons.shield_alert,
    add => fl.FluentIcons.add,
    importFile => fl.FluentIcons.download,
    tag => fl.FluentIcons.tag,
    settings => fl.FluentIcons.settings,
    timer => fl.FluentIcons.timer,
    lock => fl.FluentIcons.lock,
    search => fl.FluentIcons.search,
    synced => fl.FluentIcons.cloud,
    syncing => fl.FluentIcons.sync,
    syncOff => fl.FluentIcons.cloud_not_synced,
    syncFailed => fl.FluentIcons.warning,
    keyChanged => fl.FluentIcons.permissions,
    warning => fl.FluentIcons.warning,
    chevronRight => fl.FluentIcons.chevron_right,
    chevronDown => fl.FluentIcons.chevron_down,
    platformApple => fl.FluentIcons.cell_phone,
    platformAndroid => fl.FluentIcons.cell_phone,
    platformWeb => fl.FluentIcons.globe,
    platformServer => fl.FluentIcons.server,
    platformDesktop => fl.FluentIcons.t_v_monitor,
    platformOther => fl.FluentIcons.package,
    typeAuthKey => fl.FluentIcons.permissions,
    typeCertificate => fl.FluentIcons.certificate,
    typeProfile => fl.FluentIcons.page_list,
    typeKeystore => fl.FluentIcons.azure_key_vault,
    typeFirebase => fl.FluentIcons.flame_solid,
    typeServiceAccount => fl.FluentIcons.robot,
    typeOAuthClient => fl.FluentIcons.shield,
    typeSshKey => fl.FluentIcons.code,
    typeFile => fl.FluentIcons.page,
    typeSecret => fl.FluentIcons.asterisk,
    more => fl.FluentIcons.more,
    copy => fl.FluentIcons.copy,
    reveal => fl.FluentIcons.view,
    conceal => fl.FluentIcons.hide,
    export => fl.FluentIcons.share,
    check => fl.FluentIcons.check_mark,
    calendar => fl.FluentIcons.calendar,
    person => fl.FluentIcons.contact,
    sortAscending => fl.FluentIcons.up,
    sortDescending => fl.FluentIcons.down,
  };

  IconData get _yaru => switch (this) {
    allItems => yaru.YaruIcons.app_grid,
    expiring => yaru.YaruIcons.clock,
    expired => yaru.YaruIcons.error,
    conflicts => yaru.YaruIcons.important,
    unreadable => yaru.YaruIcons.shield_warning,
    add => yaru.YaruIcons.plus,
    importFile => yaru.YaruIcons.document_open,
    tag => yaru.YaruIcons.tag,
    settings => yaru.YaruIcons.settings,
    timer => yaru.YaruIcons.hourglass,
    lock => yaru.YaruIcons.lock,
    search => yaru.YaruIcons.search,
    synced => yaru.YaruIcons.cloud,
    syncing => yaru.YaruIcons.sync,
    syncOff => yaru.YaruIcons.network_offline,
    syncFailed => yaru.YaruIcons.sync_error,
    keyChanged => yaru.YaruIcons.key,
    warning => yaru.YaruIcons.warning,
    chevronRight => yaru.YaruIcons.pan_end,
    chevronDown => yaru.YaruIcons.pan_down,
    platformApple => yaru.YaruIcons.apple,
    platformAndroid => yaru.YaruIcons.smartphone,
    platformWeb => yaru.YaruIcons.globe,
    platformServer => yaru.YaruIcons.server,
    platformDesktop => yaru.YaruIcons.computer,
    platformOther => yaru.YaruIcons.package,
    typeAuthKey => yaru.YaruIcons.fingerprint,
    typeCertificate => yaru.YaruIcons.star,
    typeProfile => yaru.YaruIcons.script,
    typeKeystore => yaru.YaruIcons.key,
    typeFirebase => yaru.YaruIcons.thunderbolt,
    typeServiceAccount => yaru.YaruIcons.user,
    typeOAuthClient => yaru.YaruIcons.shield,
    typeSshKey => yaru.YaruIcons.terminal,
    typeFile => yaru.YaruIcons.document,
    typeSecret => yaru.YaruIcons.private_mask,
    more => yaru.YaruIcons.view_more_horizontal,
    copy => yaru.YaruIcons.copy,
    reveal => yaru.YaruIcons.eye,
    conceal => yaru.YaruIcons.hide,
    export => yaru.YaruIcons.share,
    check => yaru.YaruIcons.checkmark,
    calendar => yaru.YaruIcons.calendar,
    person => yaru.YaruIcons.user,
    sortAscending => yaru.YaruIcons.pan_up,
    sortDescending => yaru.YaruIcons.pan_down,
  };
}

/// [symbol] in the current kit's icon set.
class DesktopIcon extends StatelessWidget {
  const DesktopIcon(
    this.symbol, {
    super.key,
    this.size = 16,
    this.color,
    this.semanticLabel,
  });

  final DesktopSymbol symbol;
  final double size;
  final Color? color;
  final String? semanticLabel;

  @override
  Widget build(BuildContext context) => Icon(
    symbol.of(context.desktopKit),
    size: size,
    color: color ?? context.desktopColors.secondaryText,
    semanticLabel: semanticLabel,
  );
}
